const fs = require('fs');
const path = require('path');

// 最小限の16x16黒アイコン（PNG形式）
// Base64エンコードされた小さな黒丸アイコン
const iconBase64 = `iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAdgAAAHYBTnsmCAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAFHSURBVDiNpdM/S8NAGMbx73NJbFMhGhyqUnCQIiVUcHBxEfwDCo5OfoRODk46OTk4ODo4ODg4ODg4ODgIIjg4OIiDFhwcHEQQwUEQQQcHBwcRRPxzSZq0aZO0D7zlvXveu4d7j4MQQAQIAX4gAASBIBAEgv+CCAJBIAgEgSAQBIJAEAgCQSAIBIEgEASCQBAIAkEgCASBIBAEgkAQCAJBIAgEgSAQBIL/AiII/AoiCASBIBAEgkAQCAJBIAgEgSAQBIJAEAgCQSAIBIEgEASCQBAIAkEgCASBIBAEgkAQCAJBIAj8CiL4L4gg8CuIIBAEgkAQCAJBIAgEgSAQBIJAEAgCQSAIBIEgEASCQBAIAkEgCASBIBAEgkAQCAJBIAgEgSDwK4jgvyCCQBAIAkEgCASBIBAEgkAQCAJBIAgEgSAQBIJAEAgCQSAIBIEg8Av4BhTcaK7YPWkAAAAASUVORK5CYII=`;

const iconBuffer = Buffer.from(iconBase64, 'base64');
const iconPath = path.join(__dirname, '../assets/icon.png');

fs.writeFileSync(iconPath, iconBuffer);
console.log('✅ Icon created:', iconPath);
